"use client";

import React from "react";
import { SectionPanel } from "@/components/section-panel";
import { FileText, Download, Share2, Printer, CheckCircle } from "lucide-react";

export function ReportsDashboard({ report }: { report: { title?: string, generated_for?: string, summary?: string, sections?: { heading: string, data: unknown }[] } }) {
  return (
    <div className="space-y-6">
      {/* Top Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between bg-white/80 backdrop-blur rounded-xl border border-slate-200 p-4 shadow-sm gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
            <FileText className="w-5 h-5 text-blue-600" />
          </div>
          <div>
            <p className="font-semibold text-slate-800">{report.title}</p>
            <div className="flex items-center gap-2 text-xs text-slate-500 mt-0.5">
              <CheckCircle className="w-3 h-3 text-emerald-500" />
              Generated for: {report.generated_for}
            </div>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          <button className="flex items-center gap-2 px-3 py-1.5 bg-white border border-slate-200 text-slate-600 rounded-lg hover:bg-slate-50 text-sm font-medium transition-colors">
            <Printer className="w-4 h-4" /> Print
          </button>
          <button className="flex items-center gap-2 px-3 py-1.5 bg-white border border-slate-200 text-slate-600 rounded-lg hover:bg-slate-50 text-sm font-medium transition-colors">
            <Share2 className="w-4 h-4" /> Share
          </button>
          <button className="flex items-center gap-2 px-3 py-1.5 bg-slate-900 text-white rounded-lg hover:bg-slate-800 text-sm font-medium transition-colors shadow-sm">
            <Download className="w-4 h-4" /> Export PDF
          </button>
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1fr_300px]">
        {/* Main Document View */}
        <div className="space-y-6">
          <SectionPanel title="Executive Summary">
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-5 leading-relaxed text-slate-700">
              {report.summary}
            </div>
          </SectionPanel>

          {report.sections && report.sections.length > 0 ? (
            <div className="grid gap-6 md:grid-cols-2">
              {report.sections.map((section: { heading: string; data: unknown }) => (
                <SectionPanel key={section.heading} title={section.heading}>
                  <div className="bg-slate-900 rounded-lg p-4 h-64 overflow-auto">
                    <pre className="text-xs font-mono text-emerald-400 whitespace-pre-wrap">
                      {JSON.stringify(section.data, null, 2)}
                    </pre>
                  </div>
                </SectionPanel>
              ))}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-20 bg-white border border-dashed border-slate-300 rounded-xl">
              <FileText className="w-12 h-12 text-slate-300 mb-3" />
              <p className="text-slate-500 font-medium">No detailed sections available in this report.</p>
              <p className="text-sm text-slate-400 mt-1">Generate a new report to see data here.</p>
            </div>
          )}
        </div>

        {/* Right Sidebar - Metadata */}
        <div className="space-y-6">
          <SectionPanel title="Report Metadata">
            <div className="space-y-4">
              <div className="flex flex-col">
                <span className="text-xs font-semibold text-slate-500 uppercase">Status</span>
                <span className="inline-flex items-center gap-1.5 text-sm font-medium text-emerald-600 mt-1">
                  <span className="w-2 h-2 rounded-full bg-emerald-500"></span> Finalized
                </span>
              </div>
              <div className="flex flex-col">
                <span className="text-xs font-semibold text-slate-500 uppercase">Security Clearance</span>
                <span className="text-sm font-medium text-slate-800 mt-1">Level 4 (Confidential)</span>
              </div>
              <div className="flex flex-col">
                <span className="text-xs font-semibold text-slate-500 uppercase">Generated By</span>
                <span className="text-sm font-medium text-slate-800 mt-1">AI Intelligence Engine</span>
              </div>
              <div className="flex flex-col">
                <span className="text-xs font-semibold text-slate-500 uppercase">Data Sources</span>
                <span className="text-sm text-slate-600 mt-1 leading-tight">
                  FIR Database, Geo-Spatial Intel, Sentinel Network
                </span>
              </div>
            </div>
          </SectionPanel>
        </div>
      </div>
    </div>
  );
}
